//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenesysInt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenesysInt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM .
        /// </summary>
        internal static string ALLQRY {
            get {
                return ResourceManager.GetString("ALLQRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusion / Exclusion process ended successfully. .
        /// </summary>
        internal static string BENCHMRKEN {
            get {
                return ResourceManager.GetString("BENCHMRKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Inclusion / Exclusion process started. .
        /// </summary>
        internal static string BENCHMRKST {
            get {
                return ResourceManager.GetString("BENCHMRKST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character overflow exception, nothing more..
        /// </summary>
        internal static string CHAROVRFLOW {
            get {
                return ResourceManager.GetString("CHAROVRFLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character underflow exception, nothing more..
        /// </summary>
        internal static string CHARUNDFLOW {
            get {
                return ResourceManager.GetString("CHARUNDFLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Contact are cleared from contact list :.
        /// </summary>
        internal static string CLEAROK {
            get {
                return ResourceManager.GetString("CLEAROK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 1 FROM mm_genesys_ids WHERE genesys_id = :genesys_id AND contactlistid = :contactlistid.
        /// </summary>
        internal static string CONTIDQRY {
            get {
                return ResourceManager.GetString("CONTIDQRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle data extraction format error, unexpected Inclusion/Exclusion data format.
        /// </summary>
        internal static string DATAFORMATERR {
            get {
                return ResourceManager.GetString("DATAFORMATERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in performing DB operation, environment : .
        /// </summary>
        internal static string DBEXCEPTION {
            get {
                return ResourceManager.GetString("DBEXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection failed. .
        /// </summary>
        internal static string DBNOTCONNECTED {
            get {
                return ResourceManager.GetString("DBNOTCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request cannot be fullfilled. Contact List with same name or ID exists in creating :.
        /// </summary>
        internal static string DUPCONTLST {
            get {
                return ResourceManager.GetString("DUPCONTLST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data get from database, environment : .
        /// </summary>
        internal static string EMPTYDATA {
            get {
                return ResourceManager.GetString("EMPTYDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error in getting token: access token was not generated or got. .
        /// </summary>
        internal static string ERR_GET_TOKEN {
            get {
                return ResourceManager.GetString("ERR_GET_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in listing agent activity summary from Genesys :.
        /// </summary>
        internal static string FAILAGNTACTS {
            get {
                return ResourceManager.GetString("FAILAGNTACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in checking self organization info : .
        /// </summary>
        internal static string FAILCHKSELFINFO {
            get {
                return ResourceManager.GetString("FAILCHKSELFINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in listing contact from Genesys :.
        /// </summary>
        internal static string FAILCONTLST {
            get {
                return ResourceManager.GetString("FAILCONTLST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred creating contact list in Genesys :.
        /// </summary>
        internal static string FAILCRCONTLST {
            get {
                return ResourceManager.GetString("FAILCRCONTLST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in making Genesys API call :.
        /// </summary>
        internal static string FAILGENERICCALL {
            get {
                return ResourceManager.GetString("FAILGENERICCALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in listing some data from Genesys : .
        /// </summary>
        internal static string FAILGENERICLST {
            get {
                return ResourceManager.GetString("FAILGENERICLST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genesys error : .
        /// </summary>
        internal static string GENESYSGENERICERRMSG {
            get {
                return ResourceManager.GetString("GENESYSGENERICERRMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT genesys_id FROM mm_genesys_ids WHERE numabo = :numabo AND contactlistid = :contactlistid.
        /// </summary>
        internal static string GENIDQRY {
            get {
                return ResourceManager.GetString("GENIDQRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO mm_genesys_ids VALUES (:genesys_id, :numabo, :contactlistid).
        /// </summary>
        internal static string INSGENID {
            get {
                return ResourceManager.GetString("INSGENID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or bad proxy configuration parameter(s), details : .
        /// </summary>
        internal static string INVPROXY {
            get {
                return ResourceManager.GetString("INVPROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact List not found error, contact list ID :.
        /// </summary>
        internal static string NFNDCONTLIST {
            get {
                return ResourceManager.GetString("NFNDCONTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Json store path, Json store path not found. .
        /// </summary>
        internal static string NOTJSONSTORE {
            get {
                return ResourceManager.GetString("NOTJSONSTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E6C310D57DED0DCBAE560266AD84B22DDED05BA3030E3D18DC9ED0BCE5736995A0000C5D315B263CBE5D730D211E46B69932C0816BABA09729663AC702DDB68C5D28200A646B732278CAE42DBB2929502D6B.
        /// </summary>
        internal static string PKEY {
            get {
                return ResourceManager.GetString("PKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E6C310D57DED0DCBAE560266AD84B22DDED05BA3030E3D18DC9ED0BCE5736995A0000C5D315B263CBE5D730D211E46B69932C0816BABA09729663AC702DDB68C5D28200A646B732278CAE4.
        /// </summary>
        internal static string TKEY {
            get {
                return ResourceManager.GetString("TKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  No exclusion data deteced. Environment :.
        /// </summary>
        internal static string ZEROEXCDATA {
            get {
                return ResourceManager.GetString("ZEROEXCDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  No inclusion data detected. Environment : .
        /// </summary>
        internal static string ZEROINSDATA {
            get {
                return ResourceManager.GetString("ZEROINSDATA", resourceCulture);
            }
        }
    }
}
